---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
  label:
    service: spring-petclinic
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    service: spring-petclinic
        